const CONFIGDATA = {
  titleHeader: "Huhu xin lỗi các c nhé, chúng mình đã làm rất tốt rùi nhưng mà vẫn còn dl cuối cùng này nx thui. </br> Cố gắng hết sức để có 1 kì tập huấn thật trọn vẹn nhé!",
  descriptionHeader:
    "Đứa nào out là t feedback với anh chị đấy",
  buttonYes: "Đồng ý",
  buttonNo: "Không đồng ý",
  titleModar: "Cảm ơn cậu.",
  descriptionModar:
    "Chào ngày mới các cậuu, ngày chúng mình sẽ 0 còn đau đầu vì Đoàn tụ nữa (trừ corett phải edit recap hehe cố lên các c nhé). Thra là khum có dl nào nữa đâu vì các c done hết rùi mà =)) Tớ định nhắn tt cơ nma ngại vl. Thôi thì trải lòng 1 chút nhé. Vậy là tập huấn cũng đã kết thúc rùi ha, đặt mình vào người thgia thì 2 ngày vừa qua thật sự vô cùng tuyệt vời (trừ nhà wc tòa mình và 1 vài cái nữa) Và ý tưởng cho sự tuyệt vời đó đều nhờ tất cả các c, cùng sự giúp đỡ nhiệt tình từ ac. Vì thế tớ muốn được gửi lời cảm ơn đến tất cả các cậu. Cảm ơn 3 lsub tổng, dlinh, npk, thn vì đã 0 chỉ luôn đồng hành, keep track mà còn trực tiếp tham gia vào quá trình lên ý tưởng cùng với cto. Tớ cảm ơn Khánh Linh 😏 </br> Tớ cảm ơn Lan vì những áng văn say đắm lòng người mà cto nhờ cậu viết vội, vì những trò chơi và key visual vô cùng tuyệt vời mà c đã vất vả nghĩ ra dù cậu đang sốt rất cao, mặc dù chưa được đúng gu với ac lắm nhưng cto rất thích nó. </br> Tớ cảm ơn Hà Linh vì những lần gánh team khá mạnh mặc dù cậu đang ốm và đang đi học qsu without chuột, ê lọ điều ước của cậu đúng nghĩa đen cmnl í =)) và cả draft ava, backdrop... (th nhiều quá lười kể) mà c đã hthanh rất tốt mỗi khi cto spam ib c </br> Tớ cảm ơn Thảo, top những người anh Dũng luôn tin tưởng, kẻ định danh cho giang sơn, ai đã đặt tên cho Tập Huấn =)) Đùa chứ, cảm ơn cậu vì đã nghĩ ra 1 cái tên mà 0 chỉ anh chị duyệt luôn mà anh Dũng còn rất thích (đỉnh vl) và cả những lần cậu đã hoàn thành dl mặc kệ sinh hoạt của VITRI và sự xàm lul của Quân AP nữa he... </br> Cảm ơn Thảo Anh vì chu du - cái cto đã cố gắng pitching vs ac để giữ nma 0 đc =))) ê nma cf là nó hay nha và cả những lần fill yt lúc nửa đêm dù cho h đi ngủ là 10h của cậu, với cả m nch hay v í, kiểu nạp, nghe,... nên dù lúc đấy còn 5p đến dl nộp bcyt nma btao vẫn cố ngồi cười nốt r ms fill =)) </br> Tớ cũng cảm ơn Lâm vì dù Xuho2, trộn lòng, bạn B,C,D hay cviec ở PRO có khó khăn thế nào thì c cx luôn hthanh dl rất tốt, cảm ơn sumphonie mà ai cx muốn hồi sinh nma khó, cả những trò chơi back up khi mưa dù mưa phát là hủy luôn..., ncl cam on vi da den </br> Tớ cảm ơn Ngọc Linh vì dù bận rất nhiều cviec nhưng c cx cố gắng hoàn thành những gì cto yêu cầu. </br> Mặc dù TBD đã 0 đc tổ chức nhưng chúng mình đều đã rất cố gắng nên nhìn chung thì chương trình rất tuyệt vời rồi. Nhân đây tớ cũng muốn gửi lời xin lỗi chân thành đến các cậu vì những lúc lóng lảy đã nói ra những lời không hay, như là bảo các cậu luôn sai yêu cầu team building, mất kiểm soát ngôn từ, thiếu xót trong break việc,...Vì độ dài màn hình pc có hạn nên tớ chỉ muốn nói là các cậu rất tuyệt vời, tớ iu mnggg vl và nếu được thì t5 tuần này các c đi họp ban đầy đủ nha", 
};
